name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push model to Replicate
        run: cog push r8.im/princedatasolutions/artemis_imagery
